-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 20, 2017 at 10:25 PM
-- Server version: 10.1.21-MariaDB
-- PHP Version: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `graderank`
--

-- --------------------------------------------------------

--
-- Table structure for table `course`
--

CREATE TABLE `course` (
  `class` varchar(30) NOT NULL,
  `title` text NOT NULL,
  `description` text NOT NULL,
  `credit` double(5,2) NOT NULL,
  `college` varchar(100) NOT NULL,
  `sum` double(5,2) NOT NULL DEFAULT '0.00',
  `count` int(11) DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Dumping data for table `course`
--

INSERT INTO `course` (`class`, `title`, `description`, `credit`, `college`, `sum`, `count`) VALUES
('CS164', 'Introduction to Computer Science ', 'An introduction to the field of computer science. Exposure to core areas (selected from algorithms, artificial intelligence, computer architecture, databases, graphics, human-computer interaction, programming languages, scientific computation, software engineering) while introducing and reinforcing the importance of programming.', 3.00, 'CI', 0.00, 0),
('CS171', 'Computer Programming I ', 'Introduces fundamental concepts of computing including memory, instructions, function calls, and activation records. Covers fundamentals of structured computer programming in the language of instruction: variables, input and output, expressions, assignment statements, conditionals and branching, subprograms, parameter passing, repetition, arrays, top-down design, testing, and debugging.', 3.00, 'CI', 0.00, 0),
('CS172', 'Computer Programming II ', 'Covers object-oriented design, inheritance hierarchies, information hiding principles, string processing, recursion, good programming style, documentation, debugging, and testing.', 3.00, 'CI', 0.00, 0),
('CS175', 'Advanced Computer Programming I ', 'Advanced programming in language of instruction at an accelerated pace: introduces fundamental concepts of computing including memory, instructions, function calls, and activation records. Covers fundamentals of structured computer programming in the language of instruction: conditionals and branching, subprograms, parameter passing, repetition, arrays, top-down design, testing, and debugging. Supplements basic topics with deeper presentation of advanced techniques for those with some incoming programming experience.', 3.00, 'CI', 0.00, 0),
('CS387', 'Game AI Development ', 'This course focuses on artificial intelligence (AI) techniques for computer games. Students will learn both basic and advanced AI techniques that are used in a variety of game genres including first-person shooters, driving games, strategy games, platformers, etc. The course will emphasize the difference between traditional AI and game AI, the latter having a strong design component, focusing on creating games that are fun to play. Topics include path-finding, decision-making, strategy and machine learning in games.', 3.00, 'CI', 0.00, 0),
('CS430', 'Computer Graphics ', 'The course presents the fundamental geometric representations and drawing algorithms of computer graphics through lectures and programming assignments. The representations include lines, curves, splines, polygons, meshes, parametric surfaces and solids. The algorithms include line drawing, curve and surface evaluation, polygon filling, clipping, 3D-to-2D projection and hidden surface removal.', 3.00, 'CI', 0.00, 0),
('CS140', 'Introduction to Multimedia Programming ', 'Introduction to structured computer programming in a language designed for working with media (images, sound, video), e.g. Python/Jython. Topics include: variables, input and output, expressions, assignment statements, conditionals and branching, files, repetition, functions and parameter passing, one-dimensional and two-dimensional arrays, and media manipulation. Stresses good programming style, documentation, debugging, and testing.', 3.00, 'CI', 0.00, 0),
('CS143', 'Computer Programming Fundamentals ', 'Introduction to structured computer programming in language of instruction (e.g. C++). Topics include: variables, input and output, expressions, assignment statements, conditionals and branching, files, repetition, functions and parameter passing, arrays, and string manipulation. Stresses good programming style, documentation, debugging and testing.', 3.00, 'CI', 0.00, 0),
('CS161', 'Introduction to Computing ', 'Introduction to the computer as a tool for productivity and communications. Provides fluency in the use of industry-standard software for professional communications and presentations, data analysis, and telecommunication. Introduce automation and programming to enhance the effective use of computers and computer applications.', 3.00, 'CI', 0.00, 0),
('CS475', 'Computer and Network Security ', 'The key objective of this course is to provide a thorough understanding of technologies and methodologies with which computer networks can be protected. Topics that are covered include: key management and credentials, steganography and watermarking, networking security (VPNs, firewalls, intrusion detection) and system security policies.', 3.00, 'CI', 0.00, 0),
('CS435', 'Computational Photography ', 'Fundamentals of computational photography, an interdisciplinary field at the intersection of computer vision, graphics, and photography. Covered topics include fundamentals of cameras, novel camera designs, image manipulation, single-view modeling, and image-based rendering with an emphasis on learning the computational methods and their underlying mathematical concepts through hands-on assignments.', 3.00, 'CI', 0.00, 0),
('CS440', 'Theory of Computation ', 'Finite automata, regular sets, and regular expressions; pushdown automata, context-free languages, and normal forms for grammars; Turing machines and recursively enumerable sets; Chomsky hierarchy; computability theory.', 3.00, 'CI', 0.00, 0),
('CS441', 'Compiler Workshop I ', 'Design and implementation of compiler for specified language. Practical application and in-depth study of parsing, scanning, run-time storage management, type analysis, code generation, and error recovery.', 3.00, 'CI', 0.00, 0),
('CS442', 'Compiler Workshop II ', 'Continuation of CS 441. Advanced topics in compilation, code generation, and optimization for various programming languages and paradigms.', 3.00, 'CI', 0.00, 0),
('CS445', 'Topics in Computer Gaming ', 'Contemporary topics in the design and implementation of computer games. Topics may include game genres, psychological and sociological aspects of games, software tools and game development engines, character and behavior modeling, physical models and realism, virtual reality, graphics and animation, network-based games, performance analysis and efficiency.', 3.00, 'CI', 0.00, 0),
('CS451', 'Software Engineering ', 'Covers requirements specification, system modeling, formal methods, architectural design, object-oriented design, programming for reliability, user interface design, functional and structural testing, software reuse, and configuration management.', 3.00, 'CI', 0.00, 0),
('CS457', 'Data Structures and Algorithms I ', 'This course covers techniques for analyzing algorithms, including: elementary combinatorics, recurrence relations, and asymptotic analysis; data structures such as hash tables, red-black trees, B-trees, binomial and Fibonacci heaps, union-find trees; sorting algorithms and elementary graph algorithms.', 3.00, 'CI', 0.00, 0),
('CS458', 'Data Structures and Algorithms II ', 'This course presents algorithm design techniques such as dynamic programming, greedy methods, divide and conquer, amortized algorithms; more graph algorithms for minimum spanning trees, shortest paths, and network flows; string matching algorithms; algorithms for finding the convex hull of a discrete set of points; NP-Completeness and approximation algorithms.', 3.00, 'CI', 0.00, 0),
('CS461', 'Database Systems ', 'Covers topics including structure and function of database systems, normal form theory, data models (relational, network, and hierarchical), query processing (ISBL), relational algebra and calculus, and file structures. Includes programming project using DBMS.', 3.00, 'CI', 0.00, 0),
('CS465', 'Privacy and Trust ', 'This course will motivate the need for privacy protection and introduce basic privacy properties such as anonymity, unlinkability or unobservability. We will then discuss how these properties can be formalized, modeled and measured. The course will provide a broad overview of the state-of-the-art in privacy technologies, explain the main issues that these technologies address, what the current solutions are able to achieve, and the remaining open problems.', 3.00, 'CI', 0.00, 0),
('CS467', 'Security and Human Behavior ', 'Humans are usually the weakest link in information security. Technical measures are easily thwarted by end- user decisions. How are end user decisions made? This course examines security decisions online from the distinct perspective of economics, psychology, anthropology, evolutionary biology, and criminology. We will address topics such as System I vs. System II, mental models, risk perceptions, safety engineering, groups behaviors in primates.', 3.00, 'CI', 0.00, 0),
('CS470', 'Operating Systems Workshop ', 'Studies a modern multitasking operating system in detail, including device drivers, CPU scheduling, memory management, and file systems. Includes programming assignments that modify or enhance the operating system.', 3.00, 'CI', 0.00, 0),
('CS472', 'Computer Networks: Theory, Applications and Programming ', 'Introduction to computer networking theory, applications and programming, focusing on large heterogeneous networks. Broad topdown introductions to computer networking concepts including distributed applications, socket programming, operation system and router support, router algorithms, and sending bits over congested, noisy and unreliable communication links.', 3.00, 'CI', 0.00, 0),
('CS176', 'Advanced Computer Programming II ', 'Enhanced presentation of object-oriented design, inheritance hierarchies, information hiding principles, string processing, recursion, good programming style, documentation, debugging and testing. Includes special focus on language facilities and use of libraries.', 3.00, 'CI', 0.00, 0),
('CS190', 'Selected Computer Language ', 'Focuses on programming in a selected language of interest. Course content, language, and prerequisites may vary according to instructor, with emphasis on applications for which the language is designed. May be repeated for credit.', 3.00, 'CI', 0.00, 0),
('CS260', 'Data Structures ', 'Covers stacks, queues, linked allocation, binary trees, internal searching and sorting, hashing, and applications.', 3.00, 'CI', 0.00, 0),
('CS265', 'Advanced Programming Tools and Techniques ', 'Introduction to the basic principles of programming practice: testing, debugging, portability, performance, design alternatives, and style. Application in a variety of programming languages, programming environments, and operating systems. Introduction to tools used in the software development process for improving program functionality, performance, and robustness.', 3.00, 'CI', 0.00, 0),
('CS270', 'Mathematical Foundations of Computer Science ', 'Introduces formal logic and its connections to Computer Science. Students learn to translate statements about the behavior of computer programs into logical claims and to prove such assertions using both traditional techniques and automated tools. Considers approaches to proving termination, correctness, and safety for programs. Discusses propositional and predicate logic, logical inference, recursion and recursively defined sets, mathematical induction, and structural induction.', 3.00, 'CI', 0.00, 0),
('CS275', 'Web and Mobile App Development ', 'This course introduces students to web-based and mobile development technologies and practices, including tiered application development, Service-Oriented Architectures and associated exchange protocols, and web-database programming. This course explores development and integration of web services from well-known providers as well as services created by the student, using a mobile platform as a vehicle for interactions with the services.', 3.00, 'CI', 0.00, 0),
('CS281', 'Systems Architecture ', 'Covers internal function and organization of digital computers, including instruction sets, addressing methods, input-output architectures, central processor organization, machine language, and assembly language.', 4.00, 'CI', 0.00, 0),
('CS283', 'Systems Programming ', 'This course introduces computer systems, including interaction of hardware and software through the operating system, from the programmer\'s perspective. Three fundamental abstractions are emphasized: processes, virtual memory, and files. These abstractions provide programmers a common interface to a wide variety of hardware devices. Topics covered include linking, system level I/O, concurrent programming, and network programming.', 3.00, 'CI', 0.00, 0),
('CS481', 'Advanced Artificial Intelligence ', 'This course covers topics in representation, reasoning, and decision-making under uncertainty; learning; solving problems with time-varying properties. Assignments applying AI techniques toward building intelligent machines that interact with dynamic, uncertain worlds will be given.', 3.00, 'CI', 0.00, 0),
('SE101', 'Foundations of Software Engineering I ', 'Teaches students basic programming concepts within a software engineering process that involves specification, documentation, and testing. Programming coverage includes basic programming concepts such as the declaration and assignment of variables, standard data types, constants, conditional statements, loops, introduction to classes and methods, standard and file input/output, arrays, and strings. Process concepts emphasize good internal documentation practices, specifying functional requirements, defect tracking and analysis, and black-box testing.', 3.00, 'CI', 0.00, 0),
('CS479', 'Advanced Network Security ', 'A study of what it takes to make a network secure, starting with an analysis of the sometimes conflicting goals (e.g. anonymity vs. traceability) through the mechanisms that can be used to achieve these goals. Covers in depth both the design options available and the design decisions made in various deployed systems, including Kerberos, IPsec, SSL, and X.509.', 3.00, 'CI', 0.00, 0),
('CS476', 'High Performance Computing ', 'This course is an introduction to high performance computing, including concepts and applications. Course contents will include discussions of different types of high performance computer architectures (multi-core/multi-threaded processors, parallel computers, etc), the design, implementation, optimization and analysis of efficient algorithms for uni-processors, multi-threaded processors, parallel computers, and high performance programming.', 3.00, 'CI', 0.00, 0),
('CS432', 'Interactive Computer Graphics ', 'This is a project-oriented class that covers the concepts and programming details of interactive computer graphics. These include graphics primitives, display lists, picking, shading, rendering buffers and transformations. Students will learn an industry-standard graphics system by implementing weekly programming assignments. The course culminates with a student-defined project.', 3.00, 'CI', 0.00, 0),
('CS431', 'Advanced Rendering Techniques ', 'The creation of realistic images from 3D models is central to the development of computer graphics. The ray tracing algorithm has become one of the most popular and powerful techniques for creating photo-realistic images. This class explores the algorithmic components of ray tracing. Students implement many of these components in their class programming projects.', 3.00, 'CI', 0.00, 0),
('CS385', 'Evolutionary Computing ', 'This course covers computational intelligence approaches to problem solving for classification, adaptation, optimization, and automated control. Methods covered will include evolutionary programming/genetic algorithms, genetic programming, neural networks, swarm optimization, and fuzzy logic.', 3.00, 'CI', 0.00, 0),
('CS300', 'Applied Symbolic Computation ', 'This course covers the fundamentals of symbolic mathematical methods as embodied in symbolic mathematics software systems, including: fundamental techniques, simplification of expressions, solution of applications problems, intermediate expressions swell, basic economics of symbolic manipulation, efficient solution methods for large problems, hybrid symbolic/numeric techniques.', 3.00, 'CI', 0.00, 0),
('CS303', 'Algorithmic Number Theory and Cryptography ', 'Covers fundamental algorithms for integer arithmetic, greatest common divisor calculation, modular arithmetic, and other number theoretic computations. Algorithms are derived, implemented and analyzed for primality testing and integer factorization. Applications to cryptography are explored including symmetric and public-key cryptosystems. A cryptosystem will be implemented and methods of attack investigated.', 3.00, 'CI', 0.00, 0),
('CS338', 'Graphical User Interfaces ', 'This course covers the design and implementation of graphical user interfaces. Topics include: event-driven programming, application programmer interfaces, widgets, callback functions, windowing systems and desktops, rapid prototyping languages, multithreaded GUI\'s. A term project involving implementation of a complex application will be undertaken.', 3.00, 'CI', 0.00, 0),
('CS345', 'Computer Game Design and Development ', 'This course introduces students to the computer game design process. Students also learn how the individual skills of modeling, animation, scripting, interface design and story telling are coordinated to produce interactive media experiences for various markets, devices and purposes.', 3.00, 'CI', 0.00, 0),
('CS347', 'Experimental Game Development ', 'The goal of this course is to develop new ideas and innovations in games through the design, development, and implementation of games using short development cycles and creative thematic constraints.', 3.00, 'CI', 0.00, 0),
('CS348', 'Serious Game Development ', 'The goal of this course is to learn more about serious games, that is games used in a non-entertainment context, such as games for health, education, and persuasion, through readings and through the design, development, and implementation of serious games.', 3.00, 'CI', 0.00, 0),
('CS350', '[WI] Software Design ', 'Covers software design methods and implementation. Good design and implementation approaches will be motivated through software examples and reinforced through programming projects. Topics include architectural styles, code reuse, modularity and information hiding principles, object-oriented design patterns, design specification and formal methods, good coding and documentation practices. This is a writing intensive course.', 3.00, 'CI', 0.00, 0),
('CS352', 'Processor Architecture & Analysis ', 'This course covers performance evaluation and benchmarking, pipelining, superscalar processors, multiprocessors, and interfacing processors and peripherals. The memory hierarchy, including cache and virtual memory, are also explored from a programmer\'s perspective with high-performance computing techniques in mind.', 3.00, 'CI', 0.00, 0),
('CS360', 'Programming Language Concepts ', 'Introduces the design and implementation of modern programming languages: formal theory underlying language implementation; concerns in naming, binding, storage allocation and typing; semantics of expressions and operators, control flow, and subprograms; procedural and data abstraction; functional, logic, and object-oriented languages. Students will construct an interpreter for a nontrivial language.', 3.00, 'CI', 0.00, 0),
('CS361', 'Concurrent Programming ', 'Covers programming of concurrent, cooperating sequential processes. Studies race conditions, critical sections, mutual exclusion, process synchronization, semaphores, monitors, message passing, the rendezvous, deadlock, and starvation.', 3.00, 'CI', 0.00, 0),
('CS365', 'System Administration ', 'Fundamentals of system administration featuring hands-on practice with an industry standard operating system. Focus on installation, maintenance and management of several systems for multi-user environments.', 3.00, 'CI', 0.00, 0),
('CS370', 'Operating Systems ', 'Explores the internal algorithms and structures of operating systems: CPU scheduling, memory management, file systems, and device management. Considers the operating system as a collection of cooperating sequential processes (servers) providing an extended or virtual machine that is easier to program than the underlying hardware. Topics include virtual memory, input/output devices, disk request scheduling, deadlocks, file allocation, and security and protection.', 3.00, 'CI', 0.00, 0),
('CS377', 'Software Security ', 'Examines ways to avoid and correct programming flaws that lead to software security vulnerabilities in web applications, code implementation, user interfaces, use of cryptography, concurrency and exception handing. It also exposes students to testing processes that are specifically targeted to uncovering security flaws.', 3.00, 'CI', 0.00, 0),
('CS380', 'Artificial Intelligence ', 'Explores the foundations of artificial intelligence: production systems, heuristic programming, knowledge representation, and search algorithms. Also covers programming in an AI language. Additional topics chosen from game theory, decision support systems, pattern matching and recognition, image understanding, natural language, fuzzy and non-monotonic logic, machine learning, theorem proving, and common sense reasoning.', 3.00, 'CI', 0.00, 0),
('CS383', 'Machine Learning ', 'This course covers the fundamentals of modern statistical machine learning. Lectures will cover the theoretical foundation and algorithmic details of representative topics including probabilities and decision theory, regression, classification, graphical models, mixture models, clustering, expectation maximization, hidden Markov models, and weak learning.', 3.00, 'CI', 0.00, 0),
('SE102', 'Foundations of Software Engineering II ', 'Introduces students to additional programming concepts. Teaches students how to design, implement, and test object-oriented software applications using simple reusable components. Introduces basic techniques for creating reusable software components. Provides an overview of the software engineering as a discipline.', 3.00, 'CI', 0.00, 0),
('SE103', 'Foundations of Software Engineering III ', 'Introduces students to issues and practices for working with medium-size software systems. Teaches students basic techniques for using application frameworks. Introduces students to software development in teams and provides an overview of the software engineering professional practice.', 3.00, 'CI', 0.00, 0),
('SE210', 'Software Specification and Design I ', 'Study of the principles, practices, and techniques used to gather system requirements and document them in a requirements specification. Includes techniques for requirements discovery such as user interviews and prototyping. Introduces approaches for organizing and expressing software requirements in a requirements specification.', 3.00, 'CI', 0.00, 0),
('SE211', 'Software Specification and Design II ', 'Continues study of requirements with increasing emphasis on converting requirements into a software system design. Presents alternate approaches, techniques for evaluating specifications, specification and design tools, and use of specifications to develop system-level tests.', 3.00, 'CI', 0.00, 0),
('SE280', 'Special Topics in Software Engineering ', 'This course covers topics in software engineering. Different topics may be considered in different quarters.', 4.00, 'CI', 0.00, 0),
('SE310', 'Software Architecture I ', 'Study of macro-level software system architectures with an emphasis on approaches to interconnection and distribution of current and emerging architectural styles.', 3.00, 'CI', 0.00, 0),
('SE311', 'Software Architecture II ', 'Continues discussion of software architecture with a focus on micro-level architecture including patterns, frameworks, and component-based software engineering, and commercial off-the-shelf software.', 3.00, 'CI', 0.00, 0),
('SE320', 'Software Verification and Validation ', 'Presents theory and practice of software testing. Covers structural testing including such topics as path testing, dataflow testing, logic based testing, syntax testing, program slicing, mutation testing, fault injection, program perturbation, and testing tools. Discusses techniques for test construction and test suite evaluation, and validation against requirements and design models. Also covers methods of inspection and review at various phases of the software lifecycle.', 3.00, 'CI', 0.00, 0),
('SE410', 'Software Evolution ', 'Covers issues related to change in software systems. Addresses principles and techniques of corrective software maintenance, software enhancements, and software product family. Introduces students to issues of change in large software systems including configuration control, change and product management.', 3.00, 'CI', 0.00, 0),
('INFO101', 'Introduction to Information Technology ', 'Introduces the basic knowledge and techniques required to use computing effectively in organizations. Explores information systems, information technology and software concepts with an emphasis on how computing can be used to help organizations meet their goals.', 3.00, 'CI', 0.00, 0),
('INFO105', 'Introduction to Informatics ', 'Considers the field of informatics as the application of information and computer sciences to a specific domain. Focuses on the three components on informatics: information, users, and information and communication technologies. Topics include information needs, user groups, social media, technology evolution and diffusion of innovation.', 3.00, 'CI', 0.00, 0),
('INFO108', 'Foundations of Software ', 'Provides students with fundamental concepts about software and software representation. Topics include software and database representation, development environments, and techniques for designing, coding, testing and deploying software systems. Introduces programming concepts and activities using pair programming activities.', 3.00, 'CI', 0.00, 0),
('INFO110', 'Human-Computer Interaction I ', 'This course introduces the student to the study of computer-based user interfaces. It presents a user-interface layout and design, types and usage of interaction techniques, building a consistent look and feel throughout the interface and how to evaluate designs with users. Centered focus in evaluation of computer interfaces. It teaches the basic principles of user analysis and interface evaluation and gives a practical introduction to ergonomics.', 3.00, 'CI', 0.00, 0),
('INFO111', 'Informatics Design Workshop I ', 'Provides students with an opportunity to explore design practice through hands on experiences with contemporary prototyping platforms and methods. Introduces students to design as a component of informatics.', 3.00, 'CI', 0.00, 0),
('INFO112', 'Informatics Design Workshop II ', 'Builds on INFO 111 by providing students with an opportunity for open-ended exploration of human-centered systems design practice through a freshman design project. Design groups work with their instructor to develop an initial concept into a design deliverable.', 3.00, 'CI', 0.00, 0),
('INFO120', 'IST Seminar for Transfer Students ', 'Introduces students to academic and co-curricular aspects of university life. Includes academic functions such as writing, reading, and studying skills and co-curricular functions such as campus resources, activities, and social programs. Aids in the transition to student life and is designed to help each student achieve academic and personal success.', 2.00, 'CI', 0.00, 0),
('INFO140', 'Information Systems Laboratory I ', 'Provides hands-on experience with a variety of software products basic to current information systems. Covers products that support personal productivity in organizing, analyzing and presenting information. Addresses both local processing on personal computers and creation and use of information on the Internet.', 1.00, 'CI', 0.00, 0),
('INFO150', 'Ubiquitous Information Technologies ', 'Introduces students to computing as an integral part of life. Includes topics such as mobile computing, smart devices, sensors, location awareness, and the internet of things. Provides concepts and terminology combined with hands-on experiences constructing applications on mobile or other small computing devices.', 3.00, 'CI', 0.00, 0),
('INFO151', 'Web Systems and Services I ', 'Introduces technologies used to build leading-edge application systems and services on the World Wide Web. Coverage includes a selection of Web components such as mark-up and scripting languages and frameworks for building systems. Introduces Web programming using pair or small team programming activities.', 3.00, 'CI', 0.00, 0),
('INFO152', 'Web Systems and Services II ', 'Explores techniques used to build leading-edge application systems on the World Wide Web. Topics include Web server components of Web applications, and basic database processing. Includes Web programming using pair or small team programming activities.', 3.00, 'CI', 0.00, 0),
('INFO153', 'Applied Data Management ', 'Explores technologies used to gather, organize, store, and retrieve data in various forms. Focuses on using databases and other information management components in software systems. Topics include database servers, data management for Web applications, and data structures. Includes data management software development using pair or small team programming activities.', 3.00, 'CI', 0.00, 0),
('INFO154', 'Software System Construction ', 'Introduces considerations that make large software systems challenging to design, build, and maintain. Topics include coding standards and documentation, program architecture, verification, software evolution, and managing large software systems. Includes software modification and development using pair and team programming.', 3.00, 'CI', 0.00, 0),
('INFO200', 'Systems Analysis I ', 'Study of the principles, practices and tools of information systems analysis and design. Emphasis on learning pragmatic aspects of working as a systems analyst and employing the tools of systems analysis and design.', 3.00, 'CI', 0.00, 0),
('INFO203', 'Information Technology for Engineers ', 'Provides an introduction to relational system analysis and design and computer networking for engineering students. Covers requirements gathering, development of data flow diagrams and entity-relationship diagrams, and fundamental protocols for TCP/IP networking and routing.', 3.00, 'CI', 0.00, 0),
('INFO204', 'Nursing Informatics ', 'This course is designed to examine technology and tools of the Internet and World Wide Web with a focus on the use of cyber technology and selected computer applications. The automation of data management through information systems, expert systems, and telecommunication, and the impact of these technologies on nursing administration, education, practice and research are addressed in the context of nursing informatics. Actual problem-solving and mini-design projects on how computerization and automation can improve the efficiency of nursing care delivery will be emphasized.', 3.00, 'CI', 0.00, 0),
('INFO205', '[WI] Strategic Uses of Information Systems ', 'Familiarizes students with basic business problems and operations and provides an understanding of how information systems can be used to benefit organizations. Also introduces students to the pitfalls of developing and implementing information systems in organizations and helps students improve critical thinking skills.', 3.00, 'CI', 0.00, 0),
('INFO210', 'Database Management Systems ', 'Focuses on how to design databases for given problems, and how to use database systems effectively. Topics include database design techniques using the entity-relationship approach, techniques of translating the entity-relationship diagram into a relational schema, relational algebra, commercial query languages, and normalization techniques.', 3.00, 'CI', 0.00, 0),
('INFO215', 'Social Aspects of Information Systems ', 'Introduces social issues involved in information systems design and use, e.g., personal computing, telecommuting, computers in education, the privacy and security of stored and transmitted information, and information ownership. Explores the interaction of high technology, employment, and class structure.', 3.00, 'CI', 0.00, 0),
('INFO216', 'Issues in Information Policy ', 'Introduces students to the fundamentals of information policy, through examination of particular issues such as: privacy, intellectual property, access, and security. Students will gain an understanding of the historical foundations of information policy, read and evaluate information policies, discuss key components of information policies, and create an information policy for an organization or government entity.', 3.00, 'CI', 0.00, 0),
('INFO220', 'Geographic Information Science ', 'Explores the creation, distribution and growth of geospatial data, highlighting their uses and misuses. Structured as an applications-based course where students learn how geospatial technologies are used to turn data into maps, tables and imagery through hands-on exercises and laboratory work.', 3.00, 'CI', 0.00, 0),
('INFO240', 'Introduction to Data Science ', 'Data Science encompasses skills required for data intensive work. Students will deliver data science products and services through analysis, data transformation and data access techniques. The assignments will involve web programming, statistics, and the ability to manipulate data sets with code, following examples provided.', 3.00, 'CI', 0.00, 0),
('INFO250', 'Information Visualization ', 'Introduces the foundation and the state of the art of information visualization. Explores and reflects on the design, application, and evaluation of a diverse range of information systems. Demonstrates how a number of common types of information can be visually, intuitively and interactively represented. Provides a first-hand experience of visualizing a variety of realistic data types.', 3.00, 'CI', 0.00, 0),
('INFO300', 'Information Retrieval Systems ', 'The theoretical underpinnings of information retrieval are covered to give the student a solid base for further work with retrieval systems. Emphasis is given to the process of textual information for machine indexing and retrieval. Aspects of information retrieval covered include document description, query formulation, retrieval algorithms, query matching, and system evaluation.', 3.00, 'CI', 0.00, 0),
('INFO310', 'Human-Computer Interaction II ', 'Introduces the student to interactive computer system design. Teaches some of the basic approaches to task analysis, design, and evaluation of interactive computer systems. Applies these design principles in the development of the interface to an interactive computer system.', 3.00, 'CI', 0.00, 0),
('INFO320', 'Server Technology I ', 'Addresses information systems that have server-based architectures. Introduces students to basic concepts of servers and server-based architectures. Discusses dependence on features and capabilities of the underlying operating system. Reviews concepts of operating system, their architectures, and services. Discusses the client-server and various client-server architectures.', 4.00, 'CI', 0.00, 0),
('INFO321', 'Server Technology II ', 'Presents details of specific server platforms used to provide services to information systems applications. Prepares students to apply server technologies to information systems problems.', 4.00, 'CI', 0.00, 0),
('INFO322', 'Server Technology III ', 'Continues the study of server platform technologies for information systems applications. Prepares students to apply a wide range of server technologies to information systems problems.', 4.00, 'CI', 0.00, 0),
('INFO324', 'Team Process and Product ', 'Provides hands-on experience with working in small teams to apply processes and produce products typical of current best practices in computing and information technology organizations. Allows students to develop an integrated understanding of project life cycle phases. Examines issues of team organization and operation, problem solving, and communication.', 3.00, 'CI', 0.00, 0),
('INFO330', 'Computer Networking Technology I ', 'Presents the fundamentals of data communications and networking technologies. Focuses on the broad foundational coverall of key technologies and key concepts in network planning, design, and management. Major topics include network models, data and voice communications, local-area and wide-area technologies, IP networks and their applications and internetworking emphasizing the Internet.', 4.00, 'CI', 0.00, 0),
('INFO331', 'Computer Networking Technology II ', 'Focuses on design, construction and use of modern networks and internetworks. Prepares students to successfully create and operate modern secure networks. Major topics include LAN design and construction, internetwork architecture, WAN connectivity, security, virtual private networks and network operation in real-world environments.', 4.00, 'CI', 0.00, 0),
('INFO333', 'Introduction to Information Security ', 'Introduction to information security in modern organizations. Examines what information security is, and what motivates organizations to consider information security as a high priority. Introduces legal, ethical and professional issues, risk management, security planning, security technologies, and security implementation and maintenance.', 3.00, 'CI', 0.00, 0),
('INFO336', 'Distributed Systems Security ', 'Study of the principles, practices, and techniques to secure distributed applications, information and the infrastructure of distributed information systems. Topics include security planning, policies and models, threats and attacks, and the use and integration of distributed system security mechanisms for confidentiality, authentication, access control, and intrusion detection.', 3.00, 'CI', 0.00, 0),
('INFO340', 'Programming Internet Information Systems I ', 'This is a hands-on course on programming Internet information systems with an object-oriented programming language, currently Java. The course emphasizes programming practice. It covers fundamental concepts such as object-oriented programming, client-server programming, multi-threaded programming, graphical user interface design, and application development.', 3.00, 'CI', 0.00, 0),
('INFO341', 'Programming Internet Information Systems II ', 'Continues to develop design and programming skills for the development of Internet information systems. Studies and compares various web servers, applications servers, and different server-side programming languages. Emphasizes issues related to object-oriented design and server-side programming.', 3.00, 'CI', 0.00, 0),
('INFO350', 'Visual Analytics ', 'Introduces the aims, principles, and practical tools of visual analytics for analytic reasoning and decision making. Characterizes key issues concerning with uncertainty, incomplete and conflict information. Examines the role of interactive visual analytic reasoning processes. Provides opportunities to use advanced interactive visual analytic tools.', 3.00, 'CI', 0.00, 0),
('INFO355', 'Systems Analysis II ', 'A project-oriented course that discusses software engineering and advanced techniques of requirements modeling, prototyping and software design, particularly utilizing object-oriented techniques. The course builds upon Systems Analysis I, requiring students to apply their knowledge of systems analysis tools and techniques.', 3.00, 'CI', 0.00, 0),
('INFO360', 'Language Processing ', 'Study of the problems and techniques of processing natural language. Introduces theory of spoken language and how it differs from theories of computer-generated natural language. Includes language pattern recognition and syntactic inference, and semantic networks.', 3.00, 'CI', 0.00, 0),
('INFO365', 'Database Administration I ', 'Database Administration is a continuation of Database Management Systems, and includes the following: advanced ERD techniques, database management system internals and advanced elements of the SQL language, as well as stored procedures and triggers, specifically as demonstrated in the Oracle implementation.', 3.00, 'CI', 0.00, 0),
('INFO366', 'Database Administration II ', 'Introduces the principles and practices of database administration, particularly as they apply to commercial-grade relational database management systems. The course will include, but not be limited to, installation, systems tuning, application tuning, security, user management, backup and recovery. To this end, internals of RDBMSs will be discussed, using major commercial RDBMSs as examples. Distributed database issues will also be discussed. As time permits, other advanced issues will be addressed, such as issues of object and object-relational databases.', 3.00, 'CI', 0.00, 0),
('INFO370', 'Artificial Intelligence for Information Systems ', 'Introduction to the field of artificial intelligence (AI). Basic concepts, principles, and techniques used to achieve the goals of AI are studied. Examples and applications are specific to information systems.', 3.00, 'CI', 0.00, 0),
('INFO371', 'Data Mining with Machine Learning ', 'Introduces students to basic data mining approaches using machine learning tools. Focuses on machine learning algorithms for information inference and knowledge discovery from data. Covers major applications in data/text/web processing, analysis and mining.', 3.00, 'CI', 0.00, 0),
('INFO373', 'Digital Forensics ', 'Provides an introduction to the collection, analysis, presentation, and preservation of digital evidence according to methodologies defined by forensic science to fulfill the needs of the legal and law enforcement communities. Introduces systems understanding as an important tool for digital forensic investigation of crimes that use information technology.', 3.00, 'CI', 0.00, 0),
('INFO375', 'Introduction to Information Systems Assurance ', 'Introduction to the problem of security for modern information systems. Provides an overview of threats, both human and computer, to the security of an organization\'s data and information resources. Explores how systems may be made less vulnerable and how to respond. Examines issues of personal security in an electronic world.', 3.00, 'CI', 0.00, 0),
('INFO404', 'Nursing Informatics for the Bachelor of Science in Nursing Completion ', 'Designed for registered nurses in the RN-BSN completion program. Examines computer applications, technology, internet tools, and focuses on health care informatics context for data management, information systems and telecommunications in nursing administration, education and practice. Problem solving and mini-design projects related to increased efficiency in nursing care delivery.', 3.00, 'CI', 0.00, 0),
('INFO405', 'Social and Collaborative Computing ', 'Examines selected human, social and technical issues and concepts of computer-supported cooperative work, computer-supported collaborative learning and social networking. Topics include: the way that groups work in the networked organization; analysis and design of groupware; social networking and community-learning technologies; and future directions of these technologies.', 3.00, 'CI', 0.00, 0),
('INFO410', 'Information Technology Infrastructure ', 'Presents methods for evaluating and selecting information technologies and planning technology implementation. Emphasizes consideration of needs and issues of the organization and individuals served by the technology. Also addresses issues in management of served by the technology. Also addresses issues in management of technology after initial installation including service planning, maintenance, and evolution.', 3.00, 'CI', 0.00, 0),
('INFO415', 'Information Technology Services ', 'Introduces issues in management and delivery of IT services. Addresses needs and approaches to operational support including providing services, help desks, online support, documentation, and user training. Examines approached to defining, measuring, and analyzing service and support quality.', 3.00, 'CI', 0.00, 0),
('INFO420', 'Software Project Management ', 'The objective of this course is to study project management in the context of software systems development. The course will cover the processes, contexts, metrics, planning and management concerns of managing projects for modern software systems. This is a writing intensive course.', 3.00, 'CI', 0.00, 0),
('INFO435', 'Information Services ', 'Examines electronic services that deliver published information to an organization from external sources. Relates these services to functions such as planning, marketing, and research. Shows ways of monitoring the organizations larger environments, such as the economy, government, competitors, and new technologies. This course introduces students to the core concepts of information services as they apply to the essential techniques for retrieving, analyzing, organizing and presenting information. The skills learned in this course are transferable to any information seeking activity whether it is in a large research and development lab, or a small start-up company. The overall goal of this course is that upon completion, each student can produce a systematic and accurate method for recovering, analyzing, and disseminating needed information in any setting.', 3.00, 'CI', 0.00, 0),
('INFO440', 'Social Media Trend Spotting ', 'Explores social trend spotting to analyze, understand, visualize and present information from social media feeds, which reflect emerging social, organizational and cultural trends. Students will analyze traces from social media, bespoke discussion forums and virtual organization portals to discern the relationship between online behavior and underlying social phenomena.', 3.00, 'CI', 0.00, 0),
('INFO450', 'Expert Consultant Systems ', 'Introduces the basic concepts, techniques, and tools involved in the development of information systems based on human expertise. The course discusses the identification of expert system projects, knowledge acquisition, architectures of expert systems, inference, database and procedural considerations, verification and validation of expert systems. Provides hands-on experience in developing expert systems using an expert system programming language.', 3.00, 'CI', 0.00, 0),
('INFO480', 'Special Topics in Information Systems ', 'Selected topics of interest to students in information systems. May be repeated for credit if topic varies.', 4.00, 'CI', 0.00, 0),
('CI101', 'Computing and Informatics Design I ', 'Introduces computing and informatics through a combination of lectures and hands-on laboratory exercises. Lectures emphasize an integrated view of topic areas and systems, spanning low-level software and implementation issues to high-level use and acceptance by individuals and communities. Lab exercises allow students to explore familiar systems in unique and novel ways to better understand how these systems are designed and used.', 2.00, 'CI', 0.00, 0),
('CI102', 'Computing and Informatics Design II ', 'Introduces computing and informatics through a combination of lectures and hands on laboratory exercises. Lectures emphasize an integrated view of topic areas and systems, spanning low level software and implementation issues to high level use and acceptance by individuals and communities. Lab exercises allow students to explore familiar systems in unique and novel ways to better understand how these systems are designed and used.', 2.00, 'CI', 0.00, 0),
('CI103', 'Computing and Informatics Design III ', 'Follows CI 102 in the Computing & Informatics design sequence. Introduces computing and informatics through a combination of lectures and hands-on laboratory exercises. Lectures emphasize an integrated view of topic areas and systems, spanning low-level software and implementation issues to high-level use and acceptance by individuals and communities. Lab exercises allow students to explore familiar systems in unique and novel ways to better understand how these systems are designed and used.', 2.00, 'CI', 0.00, 0),
('CI106', 'Computing & Informatics Design Project ', 'Introduces computing and informatics through a term-long design project. Lectures emphasize an integrated view of topic areas and systems, spanning low-level software and implementation issues to high-level use and acceptance by individuals and communities. Lab exercises allow students to explore familiar systems in unique and novel ways to better understand how these systems are designed and used.', 4.00, 'CI', 0.00, 0),
('CI120', 'CCI Transfer Student Seminar ', 'Introduces students to the academic and co-curricular aspects of university life. Includes academic functions such as reflection papers, reading, and study skills, as well as co-curricular functions such as campus resources, activities, and social programs. Aids in the transition to student life at Drexel and is designed to help each student achieve academic and personal success through academic and career exploration.', 2.00, 'CI', 0.00, 0),
('CI491', '[WI] Senior Project I ', 'Part of a multi-term capstone experience involving in-depth study and application of computing and informatics. Students work in teams to develop a significant product. Requires use of a development process that includes planning, specification, design, implementation, evaluation, and documentation. This course is writing intensive.', 3.00, 'CI', 0.00, 0),
('CI492', '[WI] Senior Project II ', 'Part of a multi-term capstone experience involving in-depth study and application of computing and informatics. Students work in teams to develop a significant product. Requires use of a development process that includes planning, specification, design, implementation, evaluation, and documentation. This course is writing intensive.', 3.00, 'CI', 0.00, 0);
INSERT INTO `course` (`class`, `title`, `description`, `credit`, `college`, `sum`, `count`) VALUES
('CI493', '[WI] Senior Project III ', 'Part of a multi-term capstone experience involving in-depth study and application of computing and informatics. Students work in teams to develop a significant product. Requires use of a development process that includes planning, specification, design, implementation, evaluation, and documentation. This course is writing intensive.', 3.00, 'CI', 0.00, 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `course`
--
ALTER TABLE `course`
  ADD PRIMARY KEY (`class`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
